### ISSUE TITLE
Credits page on mobile has text below footer

### ISSUE THREAD

**Issue by ArjunSharda** [ArjunSharda/TimeConv#22]
Credits page on mobile has some text below the footer. I have tried fixing it, but need help with solving it. Any help would be greatly appreciated.

**Comment by SGI-CAPP-AT2** [comment]
@ArjunSharda I'll like to to get this issue assigned to me 
this will be before behavior 
![image](https://user-images.githubusercontent.com/77089227/185736913-571fc6a8-9a85-4602-a2b8-147ac0fe5b8f.png)
 this would be after behaviour
> check this site https://big-oh-learn.github.io/

**Comment by ArjunSharda** [comment]
👋Hey, Shaum. Thanks for interest in contributing. Do you mean a footer at the bottom or as per your website dynamic?

**Comment by SGI-CAPP-AT2** [comment]
RE:
> Hey, Shubham. Thanks for interest in contributing. Do you mean a footer at the bottom or as per your website dynamic?
@ArjunSharda yes

**Comment by ArjunSharda** [comment]
Hey,

I appreciate your help but it has been fixed now and no additional help is needed.
